version: '2.2'
services:
  sql:
    image: dbarashev/sqool-frontend-database

  postgres:
    image: postgres:10
    cpus: 0.8
    mem_limit: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes_from:
      - sql
    environment:
      - POSTGRES_PASSWORD=c0nt3sts3rv3r
    ports:
      - '5432:5432'
    networks:
      sqool:
        ipv4_address: 172.25.0.11

  app:
    image: dbarashev/sqool-frontend
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    cpus: 0.2
    mem_limit: 512M
    command: --pg-address 172.25.0.11 --pg-password c0nt3sts3rv3r --contest au2018
    environment:
      - GOOGLE_CLOUD_PROJECT=dbms-class-2017
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/gce.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sqool

  init:
    image: postgres:10
    depends_on:
      postgres:
        condition: service_healthy
    cpus: 0.1
    mem_limit: 256M
    volumes_from:
      - sql
    environment:
      - PGPASSWORD=c0nt3sts3rv3r
    command: psql -h 172.25.0.11 -U postgres -f /workspace/sqool-frontend-database.sql
    networks:
      - sqool

networks:
  sqool:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
